import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, ArrowDown, ArrowLeft, Sun, Moon, Menu, X, Github, Linkedin, Download, Plus, Minus, Lightbulb, Eye, EyeOff, Sparkles, BookOpen } from 'lucide-react';
import { projects, type Project } from './data/projects';
import { profile, skillGroups, designInterests, process, uxConcepts, uxConceptCategories, type UXConcept } from './data/profile';
import { ProjectVisual } from './components/ProjectVisual';
import './styles.css';
const links = ['Home','Work','Concepts','About','Skills','Process','Contact'];
function ResumeLink({className=''}:{className?:string}) {return profile.resume ? <a className={className} href={profile.resume} download>Resume <Download size={15}/></a> : <a className={className} href="/#resume-status" aria-label="Resume — file not yet supplied">Resume <Download size={15}/></a>}
export function App({initialPath=''}:{initialPath?:string}){
 const [menu,setMenu]=useState(false); const [theme,setTheme]=useState(()=>{try{return localStorage.getItem('theme') || (matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light')}catch{return 'light'}});
 const [showAnnotations,setShowAnnotations]=useState(false);
 const pathname = (typeof window==='undefined'?initialPath:window.location.pathname).replace(/\/$/,''); const project=projects.find(p=>pathname===`/work/${p.slug}`); const notFound=pathname!==''&&!project;
 useEffect(()=>{document.documentElement.dataset.theme=theme;try{localStorage.setItem('theme',theme)}catch{}},[theme]);
 useEffect(()=>{document.title=project?`${project.title} — Kunal Khaire`:notFound?'Page not found — Kunal Khaire':'Kunal Khaire — UI/UX Designer & Developer';const description=project?`${project.title}: ${project.description} Explore the documented capabilities, technology, and interface direction.`:'Kunal Khaire designs and builds thoughtful digital products. Explore selected work, experience, and a considered approach to UI/UX.';document.querySelector('meta[name="description"]')?.setAttribute('content',description);document.querySelector('meta[property="og:title"]')?.setAttribute('content',document.title);document.querySelector('meta[property="og:description"]')?.setAttribute('content',description)},[project,notFound]);
 useEffect(()=>{const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape'){setMenu(false);document.querySelector<HTMLButtonElement>('.menu-toggle')?.focus()}};document.addEventListener('keydown',onKey);return()=>document.removeEventListener('keydown',onKey)},[]);
 useEffect(()=>{const targets=document.querySelectorAll('.section-heading,.work-row,.about-grid,.experience-row,.skill-group,.design-focus,.process-layout,.education-grid,.achievement,.case-section,.ux-concept-card,.concepts-grid');const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in-view');observer.unobserve(entry.target)}}),{threshold:0.08});targets.forEach(el=>{el.classList.add('reveal');observer.observe(el)});const progress=document.querySelector<HTMLElement>('.scroll-progress');const update=()=>{if(progress)progress.style.transform=`scaleX(${scrollY/Math.max(1,document.documentElement.scrollHeight-innerHeight)})`};addEventListener('scroll',update,{passive:true});update();return()=>{observer.disconnect();removeEventListener('scroll',update)}},[]);
 return <><a className="skip-link" href="#main">Skip to content</a><div className="scroll-progress" aria-hidden="true"/><header className="header"><a className="wordmark" href="/" aria-label="Kunal Khaire, home">kunal<span>khaire</span><i>.</i></a><nav id="main-nav" className={menu?'nav open':'nav'} aria-label="Main navigation">{links.map(l=><a key={l} href={`/#${l.toLowerCase()}`} onClick={()=>setMenu(false)}>{l}</a>)}</nav><div className="header-actions"><button className={`annotation-toggle ${showAnnotations?'active':''}`} onClick={()=>setShowAnnotations(!showAnnotations)} aria-label={showAnnotations?'Hide UI/UX annotations':'Show UI/UX annotations'} title={showAnnotations?'Hide UI/UX concept annotations':'Show UI/UX concept annotations'}>{showAnnotations?<EyeOff size={16}/>:<Eye size={16}/>}<span className="annotation-toggle-label">{showAnnotations?'Hide':'Show'} UX</span></button><ResumeLink className="nav-resume"/><button className="icon-button" onClick={()=>setTheme(theme==='light'?'dark':'light')} aria-label={`Switch to ${theme==='light'?'dark':'light'} theme`}>{theme==='light'?<Moon size={18}/>:<Sun size={18}/>}</button><button className="icon-button menu-toggle" aria-controls="main-nav" aria-expanded={menu} aria-label={menu?'Close navigation':'Open navigation'} onClick={()=>setMenu(!menu)}>{menu?<X size={22}/>:<Menu size={22}/>}</button></div></header>
 <main id="main">{notFound?<section className="container error-page"><p className="eyebrow">404 / PAGE NOT FOUND</p><h1>A small detour.</h1><p>That page isn't here. Let's get you back to the work.</p><a className="button primary" href="/">Back to home <ArrowUpRight size={18}/></a></section>:project?<CaseStudy project={project} showAnnotations={showAnnotations}/>:<Home showAnnotations={showAnnotations}/>}</main><footer className="footer container"><a className="wordmark" href="/">kunalkhaire<i>.</i></a><span>Thoughtfully designed. Carefully built.</span><a href="/#home">Back to top ↑</a></footer></>
}
/* ── Concept annotation badge ── */
function ConceptBadge({concept,children,show}:{concept:string;children?:React.ReactNode;show:boolean}){
 const found = uxConcepts.find(c=>c.name===concept||c.id===concept);
 if(!show||!found)return children?<>{children}</>:null;
 return <div className="concept-badge-wrapper">{children}<span className="concept-badge" title={found.description}><Lightbulb size={11}/> {found.name}</span></div>
}
function HeroStudio(){const[mode,setMode]=useState('design');return <div className={`hero-studio studio-${mode}`}><div className="studio-top"><span>THE WAY I THINK</span><span>01 — 02</span></div><div className="studio-graphic" aria-hidden="true"><div className="studio-grid"/><div className="studio-orbit orbit-one"/><div className="studio-orbit orbit-two"/><span className="studio-symbol">{mode==='design'?'✳':'{ }'}</span><span className="studio-corner top-left">+</span><span className="studio-corner bottom-right">+</span></div><div className="studio-caption" key={mode}><span>{mode==='design'?'01 / DESIGN WITH INTENT':'02 / BUILD WITH CARE'}</span><strong>{mode==='design'?<>Ideas into<br/><em>interfaces.</em></>:<>Interfaces into<br/><em>products.</em></>}</strong><p>{mode==='design'?'Clarity. Hierarchy. Interaction.':'React. APIs. Connected experiences.'}</p></div><div className="studio-controls" role="group" aria-label="Explore my approach"><button aria-pressed={mode==='design'} onClick={()=>setMode('design')}>Design <span>01</span></button><button aria-pressed={mode==='build'} onClick={()=>setMode('build')}>Develop <span>02</span></button></div></div>}
function Home({showAnnotations}:{showAnnotations:boolean}){return <>
 <section className="hero container" id="home"><div className="hero-meta"><span className="eyebrow">KUNAL KHAIRE / UI/UX DESIGNER + DEVELOPER</span><span className="edition">SELECTED WORK — 2026</span></div>
 <ConceptBadge concept="visual-hierarchy" show={showAnnotations}><div className="hero-composition"><div className="hero-main"><ConceptBadge concept="above-fold" show={showAnnotations}><h1><span className="headline-line">Thoughtful</span><span className="headline-line">by <em>design.</em></span><span className="headline-line final-line">Useful by code.</span></h1></ConceptBadge><div className="hero-intro"><p>I'm Kunal — a UI/UX designer and product-focused developer turning complex ideas into clear, intuitive digital experiences.</p><ConceptBadge concept="cta-design" show={showAnnotations}><div className="hero-ctas"><a className="button primary" href="#work">Explore my work <ArrowUpRight size={19}/></a><ResumeLink className="button secondary"/></div></ConceptBadge></div><div className="hero-social-row"><div className="socials"><a href={profile.github} target="_blank" rel="noreferrer" aria-label="GitHub (opens a new tab)"><Github size={18}/></a><a href={profile.linkedin} target="_blank" rel="noreferrer" aria-label="LinkedIn (opens a new tab)"><Linkedin size={18}/></a><span className="social-rule"/><a href="#contact">Let's connect <ArrowUpRight size={15}/></a></div></div></div><HeroStudio/></div></ConceptBadge><div className="hero-baseline"><span>GOOD DESIGN FEELS SIMPLE. GREAT PRODUCTS MAKE IT WORK.</span><a href="#work">SCROLL TO EXPLORE <ArrowDown size={13}/></a></div></section>
 <section className="work-section container" id="work"><SectionHeading number="01" title="Selected work." text="Recent products and interface explorations. Each project annotated with applied UI/UX concepts."/><ConceptBadge concept="gestalt-proximity" show={showAnnotations}><div className="work-grid">{projects.map((project,i)=><article className={`work-card work-card-${i}`} key={project.slug}><a className="visual-link" href={`/work/${project.slug}`} aria-label={`View ${project.title} case study`}><ProjectVisual slug={project.slug}/></a><div className="work-copy"><div className="work-meta"><span>{project.category}</span><a className="case-link-small" href={`/work/${project.slug}`}>View study <ArrowUpRight size={14}/></a></div><h3><a href={`/work/${project.slug}`}>{project.title}</a></h3><p className="project-description">{project.description}</p><div className="tags">{project.stack.map(t=><span key={t}>{t}</span>)}</div>{project.uiuxConcepts.length>0&&<div className="project-concepts-preview"><Sparkles size={13}/><span>{project.uiuxConcepts.length} UI/UX concepts applied</span></div>}</div></article>)}</div></ConceptBadge></section>

 {/* ── NEW: UI/UX Concepts Applied Section ── */}
 <section className="concepts-section" id="concepts">
  <div className="container">
   <div className="concepts-header"><div><span className="eyebrow">02 / UI/UX CONCEPTS APPLIED</span><h2>Design is intentional.<br/>Every choice has<br/><em>a reason.</em></h2><p>This portfolio itself is a demonstration of UI/UX principles. Below are the {uxConcepts.length} concepts deliberately applied in this design, organized by discipline.</p></div><div className="concepts-stats"><div className="stat-card"><strong>{uxConcepts.length}</strong><span>Concepts Applied</span></div><div className="stat-card"><strong>{uxConceptCategories.length}</strong><span>UX Disciplines</span></div><div className="stat-card"><strong>{projects.length}</strong><span>Case Studies</span></div></div></div>
   {uxConceptCategories.map(cat=>{const items=uxConcepts.filter(c=>c.category===cat);if(!items.length)return null;return <div key={cat} className="concept-category"><h3 className="concept-category-title"><BookOpen size={18}/> {cat} <span className="concept-count">{items.length}</span></h3><div className="concepts-grid">{items.map(c=><ConceptCard key={c.id} concept={c}/>)}</div></div>})}
  </div>
 </section>

 <section className="about-section" id="about"><div className="container about-grid"><div><span className="eyebrow">03 / A LITTLE ABOUT ME</span><h2>A designer's eye.<br/>A developer's<br/><em>curiosity.</em></h2></div><ConceptBadge concept="z-pattern" show={showAnnotations}><div className="about-copy"><p className="large-copy">I'm interested in the space where clear interfaces meet useful technology.</p><p>My development background spans responsive interfaces, APIs, and full-stack applications. Through internships and project work, I've worked with the details that turn an idea into working software.</p><p>I bring that perspective to UI/UX: understand the problem, simplify the path, and build with care. I'm drawn to practical products that help people make sense of complex tasks.</p></div></ConceptBadge></div></section>
 <section className="container section skills-section" id="skills"><SectionHeading number="04" title="The tools behind the work." text="A connected toolkit, from interface to implementation."/><ConceptBadge concept="millers-law" show={showAnnotations}><div className="skill-grid">{skillGroups.map((g,i)=><div className="skill-group" key={g.title}><span className="eyebrow">0{i+1}</span><h3>{g.title}</h3><div className="tags">{g.items.map(s=><span key={s}>{s}</span>)}</div></div>)}</div></ConceptBadge><div className="design-focus"><h3>UI/UX focus</h3><p>The areas that guide my design approach and continued learning.</p><div className="tags">{designInterests.map(s=><span key={s}>{s}</span>)}</div></div></section>
 <section className="process-section" id="process"><div className="container process-layout"><div><span className="eyebrow">05 / HOW I APPROACH THE WORK</span><h2>Start with why.<br/>Make it clear.<br/><em>Keep improving.</em></h2><p>A flexible approach to design and development. The stages adapt to the project, its context, and the evidence available.</p><p className="muted small">This is my design approach, not a claim that every stage was completed on every project.</p></div><ConceptBadge concept="progressive-disclosure" show={showAnnotations}><div className="process-list">{process.map(([title,text],i)=><ProcessStep key={title} index={i} title={title} text={text}/>)}</div></ConceptBadge></div></section>
 <section className="contact-section" id="contact"><div className="container"><span className="eyebrow">06 / LET'S CONNECT</span><h2>Let's build<br/>something <em>useful.</em></h2><div className="contact-bottom"><p>Open to opportunities, collaborations,<br/>and interesting product ideas.</p><a className="button contact-button" href={profile.linkedin} target="_blank" rel="noreferrer">Connect on LinkedIn <ArrowUpRight size={19}/></a></div><div className="contact-links"><a href={profile.github} target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={17}/></a><a href={profile.linkedin} target="_blank" rel="noreferrer">LinkedIn <ArrowUpRight size={17}/></a>{profile.email?<a href={`mailto:${profile.email}`}>Email <ArrowUpRight size={17}/></a>:<span>Email · coming soon</span>}<ResumeLink/></div><p className="resume-status" id="resume-status">{profile.resume?'Download my resume using the link above.':'Resume file not yet available. Please connect on LinkedIn for more information.'}</p></div></section>
 </>}

/* ── Concept Card Component ── */
function ConceptCard({concept}:{concept:UXConcept}){
 const [expanded,setExpanded]=useState(false);
 return <div className={`ux-concept-card ${expanded?'expanded':''}`}>
  <div className="concept-card-top">
   <span className="concept-icon"><Lightbulb size={16}/></span>
   <h4>{concept.name}</h4>
  </div>
  <p className="concept-desc">{concept.description}</p>
  <button className="concept-expand" onClick={()=>setExpanded(!expanded)} aria-expanded={expanded}>
   {expanded?'Less':'Where is it applied?'} {expanded?<Minus size={14}/>:<Plus size={14}/>}
  </button>
  {expanded&&<div className="concept-details">
   <div className="concept-applied"><span className="concept-detail-label">Applied at:</span><p>{concept.appliedAt}</p></div>
   <div className="concept-principle"><span className="concept-detail-label">Principle:</span><p>{concept.principle}</p></div>
  </div>}
 </div>
}

function SectionHeading({number,title,text}:{number:string;title:string;text:string}){return <div className="section-heading"><div><span className="eyebrow">{number} / {number==='01'?'SELECTED PROJECTS':number==='02'?'UI/UX CONCEPTS':'THE NEXT CHAPTER'}</span><h2>{title}</h2></div><p>{text}</p></div>}
function ProcessStep({index,title,text}:{index:number;title:string;text:string}){const[open,setOpen]=useState(index===0);return <div className={`process-step ${open?'expanded':''}`}><h3><button onClick={()=>setOpen(!open)} aria-expanded={open} aria-controls={`process-${index}`}><span className="process-number">0{index+1}</span>{title}{open?<Minus size={18}/>:<Plus size={18}/>}</button></h3><div id={`process-${index}`} hidden={!open}><p>{text}</p></div></div>}
function CaseStudy({project:p,showAnnotations}:{project:Project;showAnnotations:boolean}){const index=projects.indexOf(p);return <article className="case-study container"><a className="text-link back-link" href="/#work"><ArrowLeft size={16}/> All selected work</a><div className="case-hero"><span className="eyebrow">PROJECT 0{index+1} / {p.category.toUpperCase()}</span><h1>{p.title}<span>.</span></h1><p>{p.description}</p><div className="case-facts"><div><span>CONTRIBUTION</span><strong>{p.role}</strong></div><div><span>PROJECT TYPE</span><strong>{p.category}</strong></div><div><span>FOCUS</span><strong>Product capabilities & interface direction</strong></div></div></div><ProjectVisual slug={p.slug}/><div className="case-layout"><nav aria-label="Case study sections" className="case-nav">{['Overview','Context','Contribution','Goals','Use case','Product structure','Design approach','UX decisions','UI/UX Concepts Applied','Key screens','Responsive experience','Technology','Challenges','Outcome','Learnings'].map((s,i)=><a href={`#study-${i}`} key={s}>{String(i+1).padStart(2,'0')} {s}</a>)}</nav><div className="case-content">
 <CaseSection i={0} title="Overview"><p>{p.context}</p></CaseSection>
 <CaseSection i={1} title="Problem / context"><p>{p.context}</p><p>The focus is the practical workflow described in the project scope. No user interviews or formal research findings were supplied.</p></CaseSection>
 <CaseSection i={2} title="My role"><p>{p.role}, covering the project capabilities listed below. The source does not specify team size, ownership boundaries, or a separate design role.</p><ul>{p.highlights.map(h=><li key={h}>{h}</li>)}</ul></CaseSection>
 <CaseSection i={3} title="Project goals"><p>{p.goals}</p></CaseSection>
 <CaseSection i={4} title="Users / use case"><p>{p.useCase}</p><p className="muted">Intended use case inferred from the documented functionality; not a validated user persona.</p></CaseSection>
 <CaseSection i={5} title="Product structure"><div className="structure-flow">{p.highlights.slice(0,3).map((h,i)=><div key={h}><span>0{i+1}</span>{h}</div>)}</div></CaseSection>
 <CaseSection i={6} title="Design approach"><p>{p.approach}</p></CaseSection>
 <CaseSection i={7} title="UI/UX decisions to explore"><ul>{p.decisions.map(d=><li key={d}>{d}</li>)}</ul><p className="muted">Proposed considerations for this portfolio concept, rather than verified decisions from the original project.</p></CaseSection>

 {/* ── NEW: UI/UX Concepts Applied in this project ── */}
 <CaseSection i={8} title="UI/UX Concepts Applied">
  {p.uiuxConcepts.length>0?<>
   <p>The following UI/UX design principles were deliberately applied in this project:</p>
   <div className="case-concepts-grid">
    {p.uiuxConcepts.map((uc,idx)=><div key={idx} className="case-concept-item">
     <div className="case-concept-header"><Lightbulb size={15}/><strong>{uc.concept}</strong></div>
     <p>{uc.application}</p>
    </div>)}
   </div>
  </>:<p>UI/UX concept documentation for this project is being developed.</p>}
 </CaseSection>

 <CaseSection i={9} title="Key screens"><p>The illustrative overview above brings the core capabilities into one visual direction. Original application screenshots were not provided.</p></CaseSection>
 <CaseSection i={10} title="Responsive experience"><p>A responsive implementation should preserve access to core actions on smaller screens. {p.slug==='smartcsv'?'Tabular data needs a contained scroll region, clear column headings, and reachable cleaning controls.':p.slug==='capstonex'?'Workflow columns can stack while retaining each project\'s status and next action.':'Dashboard panels can stack, keeping estimate context and explanatory insights together.'}</p><p className="muted">This describes a proposed responsive strategy; device testing of the original application is not documented.</p></CaseSection>

 <CaseSection i={11} title="Technology"><div className="tags">{p.stack.map(t=><span key={t}>{t}</span>)}</div></CaseSection>
 <CaseSection i={12} title="Challenges"><p>{p.challenge}</p></CaseSection>
 <CaseSection i={13} title="Outcome"><p>The documented project delivers {p.highlights.join(', ').toLowerCase()}. No measured adoption, usability results, or business outcomes were supplied.</p></CaseSection>
 <CaseSection i={14} title="Learnings & next questions"><p>{p.learning}</p><p>Further reflection would benefit from original design artifacts, implementation details, and feedback from actual use.</p></CaseSection>
 </div></div><a className="next-project" href={`/work/${projects[(index+1)%projects.length].slug}`}><span className="eyebrow">NEXT PROJECT</span><strong>{projects[(index+1)%projects.length].title} <ArrowUpRight size={36}/></strong></a></article>}
function CaseSection({i,title,children}:{i:number;title:string;children:React.ReactNode}){return <section id={`study-${i}`} className="case-section"><span className="eyebrow">{String(i+1).padStart(2,'0')}</span><h2>{title}</h2>{children}</section>}
if(typeof document!=='undefined')createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
